# Generated by Django 5.2.3 on 2025-06-30 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptilerUser', '0002_reptileruser_delete_repitileruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reptiler_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='reptilerUser.reptileruser')),
            ],
        ),
    ]
