# Generated by Django 5.2.3 on 2025-06-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptilerUser', '0003_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reptileruser',
            name='name_public',
        ),
    ]
