# Generated by Django 5.2.3 on 2025-08-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptilerUser', '0004_remove_reptileruser_name_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='plot',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='video',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='signal',
            field=models.FileField(blank=True, null=True, upload_to='signals/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
