# Generated by Django 5.2.3 on 2025-08-18 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptilerUser', '0005_video_plot_video_processed_video_video_signal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='progresso',
            field=models.IntegerField(default=0, help_text='Progresso do processamento em porcentagem', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
